version: '3.8'

services:
  delrey-daemon:
    image: delrey-daemon:latest
    container_name: delrey-daemon
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    env_file: ../.env
    restart: on-failure