# Delrey Master

### Session
WEBSOCKET ws://192.168.0.200:8070/session?whoami=test

### GET Status
GET http://192.168.0.200:8070/status

### GET Run
GET http://192.168.0.200:8070/runs/ea020c4e-d29b-4cd1-82d4-f46896818e03
Content-Type: application/json
Authorization: {{token}}

### POST Run
POST http://192.168.0.200:8070/runs
Content-Type: application/json
Authorization: {{token}}

{
    "command": {
        "name": "pwda",
        "arguments": [
        ]
    },
    "host": "test"
}