# Delrey Master

### Session
WEBSOCKET ws://192.168.0.200:8070/session?whoami=test

### GET Status
GET http://192.168.0.200:8070/status

### GET Run
GET http://192.168.0.200:8070/runs/id
Authorization: {{token}}

### GET Runs
GET http://192.168.0.200:8070/runs?host=test
Authorization: {{token}}

### POST Run
POST http://192.168.0.200:8070/runs?wait=true
Content-Type: application/json
Authorization: {{token}}

{
    "command": "pwd",
    "host": "test"
}