name: Build

on:
  push:
    branches:
      - main
      - dev

  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build
        uses: gradle/gradle-build-action@0d13054264b0bb894ded474f08ebb30921341cee
        with:
          arguments: delrey-master:build delrey-daemon:shadowJar delrey-client:build

      - name: Upload Master Artifact
        uses: actions/upload-artifact@v3.0.0
        with:
          name: delrey-master
          path: "./delrey-master/build/libs"

      - name: Upload Daemon Artifact
        uses: actions/upload-artifact@v3.0.0
        with:
          name: delrey-daemon
          path: "./delrey-daemon/build/libs"

      - name: Upload Client Library Artifact
        uses: actions/upload-artifact@v3.0.0
        with:
          name: delrey-client
          path: "./delrey-client/build/libs"